name: Task2 Ansible

on:
  workflow_dispatch:

jobs:
  ansible:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: task2

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y ansible

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          printf '%s\n' "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Disable SSH host key checking
        run: |
          echo "Host *" > ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile /dev/null" >> ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Show inventory
        run: cat inventory.ini

      - name: Test connection
        run: ansible all -i inventory.ini -m ping

      - name: Dry run
        run: ansible-playbook -i inventory.ini playbook.yml --check

      - name: Apply playbook
        run: ansible-playbook -i inventory.ini playbook.yml
